### ISSUE TITLE
AnyEdit Tools is unable to create property page on MacOS under LiClipse

### ISSUE THREAD

**Issue by kwloafman** [iloveeclipse/anyedittools#141]
MacOs 12.4 Intel
LiClipse 8.2.0

Unable to create the selected property page.
de.loskutov.anyedit.ui.preferences.ProjectPreferencePage cannot be found by de.loskutov.anyedit.AnyEditTools_2.7.2.202203051053

--- trace from .log ---
```
!MESSAGE Plug-in de.loskutov.anyedit.AnyEditTools was unable to load class de.loskutov.anyedit.actions.SaveToFilePartici
pant.
!STACK 0
java.lang.ClassNotFoundException: de.loskutov.anyedit.actions.SaveToFileParticipant cannot be found by de.loskutov.anyedit.AnyEditTools_2.7.2.202203051053
        at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:516)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:511)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:403)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:616)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
        at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
        at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
        at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
        at org.eclipse.ui.internal.console.ConsolePageParticipantExtension.createDelegate(ConsolePageParticipantExtension.java:69)
        at org.eclipse.ui.internal.console.ConsoleManager.getPageParticipants(ConsoleManager.java:441)
        at org.eclipse.ui.internal.console.ConsoleView.doCreatePage(ConsoleView.java:332)
        at org.eclipse.ui.part.PageBookView.createPage(PageBookView.java:369)
        at org.eclipse.ui.part.PageBookView.partActivated(PageBookView.java:696)
        at org.eclipse.ui.internal.console.ConsoleView.lambda$0(ConsoleView.java:412)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4306)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3929)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
        at com.brainwy.liclipse.rcp.IDEApplication.start(IDEApplication.java:236)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by iloveeclipse** [comment]
I assume this is a problem of the LiClipse own AnyEdit fork, please open bug there. 
I don't ship 2.7.2.202203051053 version, latest official one is [2.7.2.202006062100](https://github.com/iloveeclipse/anyedittools/releases/download/2.7.2/de.loskutov.anyedit.AnyEditTools_2.7.2.202006062100.jar)
